# Generated by Django 4.0.3 on 2022-03-29 13:35

from django.db import migrations, models
import forms.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя ученика')),
                ('subm', models.BooleanField(default=False, validators=[forms.validators.validate_true], verbose_name='Согласен с условиями')),
                ('slug', models.CharField(default='i6d9-02201', max_length=100, unique=True, verbose_name='Идентификатор')),
                ('d1', models.BooleanField(default=False, verbose_name='Второй иностранный язык (Б)')),
                ('d2', models.BooleanField(default=False, verbose_name='География (Б)')),
                ('d3', models.BooleanField(default=False, verbose_name='Обществознание (Б)')),
                ('d4', models.BooleanField(default=False, verbose_name='Теория познания (Б)')),
                ('d5', models.BooleanField(default=False, verbose_name='Информатика (Б)')),
                ('d6', models.BooleanField(default=False, verbose_name='Естествознание (Б)')),
                ('d7', models.BooleanField(default=False, verbose_name='Диалоги с Чеховым')),
                ('d8', models.BooleanField(default=False, verbose_name='Современная литература в жанровом аспекте')),
                ('d9', models.BooleanField(default=False, verbose_name='Риторика')),
                ('d10', models.BooleanField(default=False, verbose_name='История философии')),
                ('d11', models.BooleanField(default=False, verbose_name='История мировой культуры')),
            ],
            options={
                'verbose_name': 'ученик',
                'verbose_name_plural': '10 гум',
            },
        ),
    ]
