# Generated by Django 4.0.3 on 2022-04-24 08:56

from django.db import migrations, models
import forms.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя ученика')),
                ('subm', models.BooleanField(default=False, validators=[forms.validators.validate_true], verbose_name='Согласен с условиями')),
                ('slug', models.CharField(default='0g1c1-e92b4', max_length=100, unique=True, verbose_name='Идентификатор')),
                ('attached', models.BooleanField(default=False, verbose_name='Экспортировать')),
                ('d1', models.BooleanField(default=False, verbose_name='Второй иностранный язык (Б)')),
                ('d2', models.BooleanField(default=False, verbose_name='География (Б)')),
                ('d3', models.BooleanField(default=False, verbose_name='Обществознание (Б)')),
                ('d4', models.BooleanField(default=False, verbose_name='Теория познания (Б)')),
                ('d5', models.BooleanField(default=False, verbose_name='Информатика (Б)')),
                ('d6', models.BooleanField(default=False, verbose_name='Естествознание (Б)')),
                ('d7', models.BooleanField(default=False, verbose_name='Диалоги с Чеховым')),
                ('d8', models.BooleanField(default=False, verbose_name='Современная литература в жанровом аспекте')),
                ('d9', models.BooleanField(default=False, verbose_name='Риторика')),
                ('d10', models.BooleanField(default=False, verbose_name='История философии')),
                ('d11', models.BooleanField(default=False, verbose_name='История мировой культуры')),
            ],
            options={
                'verbose_name': 'ученик',
                'verbose_name_plural': '10 гум',
            },
        ),
        migrations.CreateModel(
            name='Sgum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя ученика')),
                ('subm', models.BooleanField(default=False, validators=[forms.validators.validate_true], verbose_name='Согласен с условиями')),
                ('slug', models.CharField(default='0g1c1-e92b4', max_length=100, unique=True, verbose_name='Идентификатор')),
                ('attached', models.BooleanField(default=False, verbose_name='Экспортировать')),
                ('d1', models.BooleanField(default=False, verbose_name='География (Б)')),
                ('d2', models.BooleanField(default=False, verbose_name='Теория познания (Б)')),
                ('d3', models.BooleanField(default=False, verbose_name='МХК (Б)')),
                ('d4', models.BooleanField(default=False, verbose_name='Информатика (Б)')),
                ('d5', models.BooleanField(default=False, verbose_name='Естествознание (Б)')),
                ('d6', models.BooleanField(default=False, verbose_name='Зарубежная литература')),
                ('d7', models.BooleanField(default=False, verbose_name='Современная литература в жанровом аспекте')),
                ('d8', models.BooleanField(default=False, verbose_name='Диалоги с Чеховым')),
                ('d9', models.BooleanField(default=False, verbose_name='Политология')),
                ('d10', models.BooleanField(default=False, verbose_name='Социология')),
                ('d11', models.BooleanField(default=False, verbose_name='История философии')),
            ],
            options={
                'verbose_name': 'ученик',
                'verbose_name_plural': '10 соцгум',
            },
        ),
        migrations.CreateModel(
            name='SocEk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя ученика')),
                ('subm', models.BooleanField(default=False, validators=[forms.validators.validate_true], verbose_name='Согласен с условиями')),
                ('slug', models.CharField(default='0g1c1-e92b4', max_length=100, unique=True, verbose_name='Идентификатор')),
                ('attached', models.BooleanField(default=False, verbose_name='Экспортировать')),
                ('d1', models.BooleanField(default=False, verbose_name='Теория познания (Б)')),
                ('d2', models.BooleanField(default=False, verbose_name='МХК (Б)')),
                ('d3', models.BooleanField(default=False, verbose_name='География (Б)')),
                ('d4', models.BooleanField(default=False, verbose_name='Информатика (Б)')),
                ('d5', models.BooleanField(default=False, verbose_name='Естествознание (Б)')),
                ('d6', models.BooleanField(default=False, verbose_name='Экономическая география')),
                ('d7', models.BooleanField(default=False, verbose_name='История философии ')),
                ('d8', models.BooleanField(default=False, verbose_name='Сложные математические задачи')),
            ],
            options={
                'verbose_name': 'ученик',
                'verbose_name_plural': '10 соцэк',
            },
        ),
    ]
