# Generated by Django 4.0.3 on 2022-03-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gum',
            name='slug',
            field=models.CharField(default='qzd9c-c4474', max_length=100, unique=True, verbose_name='Идентификатор'),
        ),
    ]
