# Generated by Django 3.2.9 on 2022-03-24 18:06

from django.db import migrations, models
import forms.validators


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя ученика')),
                ('d1', models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_two], verbose_name='Данные')),
                ('d2', models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_two], verbose_name='Данные')),
                ('d3', models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_one], verbose_name='Данные')),
                ('d4', models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_one], verbose_name='Данные')),
                ('d5', models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_two], verbose_name='Данные')),
                ('d6', models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_two], verbose_name='Данные')),
                ('d7', models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_one], verbose_name='Данные')),
                ('d8', models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_one], verbose_name='Данные')),
                ('d9', models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_one], verbose_name='Данные')),
                ('d10', models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_one], verbose_name='Данные')),
                ('d11', models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_three], verbose_name='Данные')),
                ('d12', models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_three], verbose_name='Данные')),
                ('d13', models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_two], verbose_name='Данные')),
                ('d14', models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_two], verbose_name='Данные')),
                ('d15', models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_one], verbose_name='Данные')),
                ('d16', models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_one], verbose_name='Данные')),
                ('d17', models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_one], verbose_name='Данные')),
                ('d18', models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_one], verbose_name='Данные')),
                ('d19', models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_one], verbose_name='Данные')),
                ('d20', models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_one], verbose_name='Данные')),
                ('d21', models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_two], verbose_name='Данные')),
                ('d22', models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_two], verbose_name='Данные')),
                ('d23', models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_two], verbose_name='Данные')),
                ('d24', models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_two], verbose_name='Данные')),
                ('d25', models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_two], verbose_name='Данные')),
                ('d26', models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_two], verbose_name='Данные')),
                ('subm', models.BooleanField(default=False, verbose_name='Согласен с условиями')),
            ],
            options={
                'verbose_name': 'ученик',
                'verbose_name_plural': 'ученики',
            },
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
