# Generated by Django 4.0.3 on 2022-04-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fizmat',
            name='slug',
            field=models.CharField(default='c5973-4381a', max_length=100, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='gum',
            name='slug',
            field=models.CharField(default='c5973-4381a', max_length=100, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='matinf',
            name='slug',
            field=models.CharField(default='c5973-4381a', max_length=100, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='sgum',
            name='slug',
            field=models.CharField(default='c5973-4381a', max_length=100, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='socek',
            name='slug',
            field=models.CharField(default='c5973-4381a', max_length=100, unique=True, verbose_name='Идентификатор'),
        ),
    ]
