# Generated by Django 4.0.3 on 2022-03-25 05:49

from django.db import migrations, models
import forms.validators


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20220324_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gum',
            options={'verbose_name': 'ученик', 'verbose_name_plural': '10 гум'},
        ),
        migrations.AlterField(
            model_name='gum',
            name='subm',
            field=models.BooleanField(default=False, validators=[forms.validators.validate_true], verbose_name='Согласен с условиями'),
        ),
    ]
