# Generated by Django 4.0.3 on 2022-04-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_matinf_alter_gum_slug_alter_sgum_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matinf',
            options={'verbose_name': 'ученик', 'verbose_name_plural': '10 матинф'},
        ),
        migrations.AlterField(
            model_name='gum',
            name='slug',
            field=models.CharField(default='je1f-e2bcd', max_length=100, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='matinf',
            name='slug',
            field=models.CharField(default='je1f-e2bcd', max_length=100, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='sgum',
            name='slug',
            field=models.CharField(default='je1f-e2bcd', max_length=100, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='socek',
            name='slug',
            field=models.CharField(default='je1f-e2bcd', max_length=100, unique=True, verbose_name='Идентификатор'),
        ),
    ]
