# Generated by Django 4.0.3 on 2022-03-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_gum_options_alter_gum_subm'),
    ]

    operations = [
        migrations.AddField(
            model_name='gum',
            name='slug',
            field=models.CharField(default='1wd62-58998', max_length=100, unique=True),
        ),
    ]
