# Generated by Django 4.0.3 on 2022-04-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_sgum_gum_attached_alter_gum_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gum',
            name='slug',
            field=models.CharField(default='ga5b-26df1', max_length=100, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='sgum',
            name='slug',
            field=models.CharField(default='ga5b-26df1', max_length=100, unique=True, verbose_name='Идентификатор'),
        ),
    ]
