# Generated by Django 4.0.3 on 2022-03-25 22:11

from django.db import migrations, models
import forms.validators


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_gum_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gum',
            name='d1',
            field=models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_two], verbose_name='Второй иностранный язык 10'),
        ),
        migrations.AlterField(
            model_name='gum',
            name='d10',
            field=models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_one], verbose_name='Информатика 11'),
        ),
        migrations.AlterField(
            model_name='gum',
            name='d11',
            field=models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_three], verbose_name='Естествознание 10'),
        ),
        migrations.AlterField(
            model_name='gum',
            name='d12',
            field=models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_three], verbose_name='Естествознание 11'),
        ),
        migrations.AlterField(
            model_name='gum',
            name='d13',
            field=models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_two], verbose_name='Зарубежная литература 10'),
        ),
        migrations.AlterField(
            model_name='gum',
            name='d14',
            field=models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_two], verbose_name='Зарубежная литература 11'),
        ),
        migrations.AlterField(
            model_name='gum',
            name='d15',
            field=models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_one], verbose_name='Диалоги с Чеховым 10'),
        ),
        migrations.AlterField(
            model_name='gum',
            name='d16',
            field=models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_one], verbose_name='Диалоги с Чеховым 11'),
        ),
        migrations.AlterField(
            model_name='gum',
            name='d17',
            field=models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_one], verbose_name='Современная литература в жанровом аспекте 10'),
        ),
        migrations.AlterField(
            model_name='gum',
            name='d18',
            field=models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_one], verbose_name='Современная литература в жанровом аспекте 11'),
        ),
        migrations.AlterField(
            model_name='gum',
            name='d19',
            field=models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_one], verbose_name='Риторика 10'),
        ),
        migrations.AlterField(
            model_name='gum',
            name='d2',
            field=models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_two], verbose_name='Второй иностранный язык 11'),
        ),
        migrations.AlterField(
            model_name='gum',
            name='d20',
            field=models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_one], verbose_name='Риторика 11'),
        ),
        migrations.AlterField(
            model_name='gum',
            name='d21',
            field=models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_two], verbose_name='Сложные аспекты истории России c древнейших времен до конца XIX века 10'),
        ),
        migrations.AlterField(
            model_name='gum',
            name='d22',
            field=models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_two], verbose_name='Сложные аспекты истории России c древнейших времен до конца XIX века 11'),
        ),
        migrations.AlterField(
            model_name='gum',
            name='d23',
            field=models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_two], verbose_name='История философии 10'),
        ),
        migrations.AlterField(
            model_name='gum',
            name='d24',
            field=models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_two], verbose_name='История философии 11'),
        ),
        migrations.AlterField(
            model_name='gum',
            name='d25',
            field=models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_two], verbose_name='История мировой культуры 10'),
        ),
        migrations.AlterField(
            model_name='gum',
            name='d26',
            field=models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_two], verbose_name='История мировой культуры 11'),
        ),
        migrations.AlterField(
            model_name='gum',
            name='d3',
            field=models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_one], verbose_name='География 10'),
        ),
        migrations.AlterField(
            model_name='gum',
            name='d4',
            field=models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_one], verbose_name='География 11'),
        ),
        migrations.AlterField(
            model_name='gum',
            name='d5',
            field=models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_two], verbose_name='Обществознание 10'),
        ),
        migrations.AlterField(
            model_name='gum',
            name='d6',
            field=models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_two], verbose_name='Обществознание 11'),
        ),
        migrations.AlterField(
            model_name='gum',
            name='d7',
            field=models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_one], verbose_name='Теория познания 10'),
        ),
        migrations.AlterField(
            model_name='gum',
            name='d8',
            field=models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_one], verbose_name='Теория познания 11'),
        ),
        migrations.AlterField(
            model_name='gum',
            name='d9',
            field=models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_one], verbose_name='Информатика 10'),
        ),
        migrations.AlterField(
            model_name='gum',
            name='slug',
            field=models.CharField(default='x4d2c-7c5f4', max_length=100, unique=True),
        ),
    ]
