# Generated by Django 4.0.3 on 2022-04-27 15:04

from django.db import migrations, models
import forms.validators


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_alter_matinf_options_alter_gum_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FizMat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя ученика')),
                ('subm', models.BooleanField(default=False, validators=[forms.validators.validate_true], verbose_name='Согласен с условиями')),
                ('slug', models.CharField(default='eg9b1-02bc4', max_length=100, unique=True, verbose_name='Идентификатор')),
                ('attached', models.BooleanField(default=False, verbose_name='Экспортировать')),
                ('d1', models.BooleanField(default=False, verbose_name='Обществознание (Б)')),
                ('d2', models.BooleanField(default=False, verbose_name='География (Б)')),
                ('d3', models.BooleanField(default=False, verbose_name='МХК (Б)')),
                ('d4', models.BooleanField(default=False, verbose_name='Теория познания (Б)')),
                ('d5', models.BooleanField(default=False, verbose_name='Биология (Б)')),
                ('d6', models.BooleanField(default=False, verbose_name='Химия (Б)')),
                ('d7', models.BooleanField(default=False, verbose_name='Астрономия')),
                ('d8', models.BooleanField(default=False, verbose_name='Избранные главы учебников естественных наук')),
            ],
            options={
                'verbose_name': 'ученик',
                'verbose_name_plural': '10 физмат',
            },
        ),
        migrations.AlterField(
            model_name='gum',
            name='slug',
            field=models.CharField(default='eg9b1-02bc4', max_length=100, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='matinf',
            name='slug',
            field=models.CharField(default='eg9b1-02bc4', max_length=100, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='sgum',
            name='slug',
            field=models.CharField(default='eg9b1-02bc4', max_length=100, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='socek',
            name='slug',
            field=models.CharField(default='eg9b1-02bc4', max_length=100, unique=True, verbose_name='Идентификатор'),
        ),
    ]
