# Generated by Django 4.0.3 on 2022-04-29 10:57

from django.db import migrations, models
import forms.validators


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_him_alter_fizmat_slug_alter_fiztech_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя ученика')),
                ('subm', models.BooleanField(default=False, validators=[forms.validators.validate_true], verbose_name='Согласен с условиями')),
                ('slug', models.CharField(default='xm9b8-ef8b3', max_length=100, unique=True, verbose_name='Идентификатор')),
                ('attached', models.BooleanField(default=False, verbose_name='Экспортировать')),
                ('d1', models.BooleanField(default=False, verbose_name='Обществознание (Б)')),
                ('d2', models.BooleanField(default=False, verbose_name='География (Б)')),
                ('d3', models.BooleanField(default=False, verbose_name='МХК (Б)')),
                ('d4', models.BooleanField(default=False, verbose_name='Теория познания (Б)')),
                ('d5', models.BooleanField(default=False, verbose_name='Информатика (Б)')),
                ('d6', models.BooleanField(default=False, verbose_name='Физика (Б)')),
                ('d7', models.BooleanField(default=False, verbose_name='Решение сложных задач по математике')),
                ('d8', models.BooleanField(default=False, verbose_name='Информатика в задачах')),
                ('d9', models.BooleanField(default=False, verbose_name='Сложные вопросы ботаники, зоологии, анатомии')),
                ('d10', models.BooleanField(default=False, verbose_name='Химические задачи повышенной сложности')),
                ('d11', models.BooleanField(default=False, verbose_name='Биологический практикум')),
            ],
            options={
                'verbose_name': 'ученик',
                'verbose_name_plural': '10 хим',
            },
        ),
        migrations.AlterField(
            model_name='fizmat',
            name='slug',
            field=models.CharField(default='xm9b8-ef8b3', max_length=100, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='fiztech',
            name='slug',
            field=models.CharField(default='xm9b8-ef8b3', max_length=100, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='gum',
            name='slug',
            field=models.CharField(default='xm9b8-ef8b3', max_length=100, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='him',
            name='slug',
            field=models.CharField(default='xm9b8-ef8b3', max_length=100, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='matinf',
            name='slug',
            field=models.CharField(default='xm9b8-ef8b3', max_length=100, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='sgum',
            name='slug',
            field=models.CharField(default='xm9b8-ef8b3', max_length=100, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='socek',
            name='slug',
            field=models.CharField(default='xm9b8-ef8b3', max_length=100, unique=True, verbose_name='Идентификатор'),
        ),
    ]
