# Generated by Django 4.0.3 on 2022-03-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_alter_gum_d1_alter_gum_d10_alter_gum_d11_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gum',
            name='slug',
            field=models.CharField(max_length=100, unique=True, verbose_name='ID'),
        ),
    ]
