# Generated by Django 4.0.3 on 2022-04-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_bio_alter_fizmat_slug_alter_fiztech_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bio',
            options={'verbose_name': 'ученик', 'verbose_name_plural': '10 био'},
        ),
        migrations.AlterField(
            model_name='bio',
            name='slug',
            field=models.CharField(default='62939-24e62', max_length=100, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='fizmat',
            name='slug',
            field=models.CharField(default='62939-24e62', max_length=100, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='fiztech',
            name='slug',
            field=models.CharField(default='62939-24e62', max_length=100, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='gum',
            name='slug',
            field=models.CharField(default='62939-24e62', max_length=100, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='him',
            name='slug',
            field=models.CharField(default='62939-24e62', max_length=100, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='matinf',
            name='slug',
            field=models.CharField(default='62939-24e62', max_length=100, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='sgum',
            name='slug',
            field=models.CharField(default='62939-24e62', max_length=100, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='socek',
            name='slug',
            field=models.CharField(default='62939-24e62', max_length=100, unique=True, verbose_name='Идентификатор'),
        ),
    ]
