# Generated by Django 4.0.3 on 2022-04-21 18:42

from django.db import migrations, models
import forms.validators


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_alter_gum_slug_alter_sgum_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocEk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя ученика')),
                ('subm', models.BooleanField(default=False, validators=[forms.validators.validate_true], verbose_name='Согласен с условиями')),
                ('slug', models.CharField(default='tq14c-8ec68', max_length=100, unique=True, verbose_name='Идентификатор')),
                ('attached', models.BooleanField(default=False, verbose_name='Экспортировать')),
                ('d1', models.BooleanField(default=False, verbose_name='Теория познания (Б)')),
                ('d2', models.BooleanField(default=False, verbose_name='МХК (Б)')),
                ('d3', models.BooleanField(default=False, verbose_name='География (Б)')),
                ('d4', models.BooleanField(default=False, verbose_name='Информатика (Б)')),
                ('d5', models.BooleanField(default=False, verbose_name='Естествознание (Б)')),
                ('d6', models.BooleanField(default=False, verbose_name='Экономическая география')),
                ('d7', models.BooleanField(default=False, verbose_name='История философии ')),
                ('d8', models.BooleanField(default=False, verbose_name='Сложные математические задачи')),
            ],
            options={
                'verbose_name': 'ученик',
                'verbose_name_plural': '10 соцэк',
            },
        ),
        migrations.AlterField(
            model_name='gum',
            name='slug',
            field=models.CharField(default='tq14c-8ec68', max_length=100, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='sgum',
            name='slug',
            field=models.CharField(default='tq14c-8ec68', max_length=100, unique=True, verbose_name='Идентификатор'),
        ),
    ]
