# Generated by Django 4.0.3 on 2022-03-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_alter_gum_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gum',
            name='slug',
            field=models.CharField(default='cyd4-36621', max_length=100, unique=True, verbose_name='ID'),
        ),
    ]
