# Generated by Django 4.0.3 on 2022-03-26 09:19

from django.db import migrations, models
import forms.validators


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_alter_gum_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='gum',
            name='d27',
            field=models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_ten], verbose_name='Внеурочная деятельность 10'),
        ),
        migrations.AddField(
            model_name='gum',
            name='d28',
            field=models.PositiveSmallIntegerField(default=0, validators=[forms.validators.validate_ten], verbose_name='Внеурочная деятельность 11'),
        ),
        migrations.AlterField(
            model_name='gum',
            name='slug',
            field=models.CharField(default='vwd2b-6f044', max_length=100, unique=True, verbose_name='ID'),
        ),
    ]
