# Generated by Django 3.2.9 on 2022-03-24 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Texts',
        ),
    ]
